spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  driver-class-name: org.postgresql.Driver
  mvc:
    view:
      prefix: /WEB-INF/JSP/
      suffix: .jsp
youtube:
  APIkey:
